# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1_s:
    has_position_limits: true
    min_position: -2.3061696722763
    max_position: 2.3061696722763
    has_velocity_limits: true
    max_velocity: 0.654498
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2_l:
    has_position_limits: true
    min_position: -0.454758191809841
    max_position: 0.862864192922348
    has_velocity_limits: true
    max_velocity: 0.549779
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3_u:
    has_position_limits: true
    min_position: -1.2217389988098
    max_position: 1.15048559119511
    has_velocity_limits: true
    max_velocity: 0.715585
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4_r:
    has_position_limits: true
    min_position: -3.31613921546937
    max_position: 3.31613921546937
    has_velocity_limits: true
    max_velocity: 0.959931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5_b:
    has_position_limits: true
    min_position: -2.03259644867761
    max_position: 1.79435005763183
    has_velocity_limits: true
    max_velocity: 0.959931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6_t:
    has_position_limits: true
    min_position: -6.28319067160695
    max_position: 6.28319067160695
    has_velocity_limits: true
    max_velocity: 1.74533
    has_acceleration_limits: false
    max_acceleration: 0
